mongo_repl_set = 'ceilo_repl_set'
db_user = 'ceilometer'
db_passwd = '<REDACTED>'
db_server = 'ceilo-mongo-04-snet.preprod-ord.ohthree.com'
db_name = 'ceilometer'
collection_name = 'coll_02'
log_frequency_docs = 1000
num_docs = 500000
num_traits_per_doc = 120
rand_int_start = 12897
rand_int_range = 40
timestamp_start = 1262304000
timestamp_end = 1356955199

events_pool = {
    'create_start': 'compute.instance.create.start',
    'create_end': 'compute.instance.create.end',
    'rebuild_start': 'compute.instance.rebuild.start',
    'rebuild_end': 'compute.instance.rebuild.end',
    'resize_prep_start': 'compute.instance.resize.prep.start',
    'resize_prep_end': 'compute.instance.resize.prep.end',
    'resize_revert_start': 'compute.instance.resize.revert.start',
    'resize_revert_end': 'compute.instance.resize.revert.end',
    'resize_finish_end': 'compute.instance.finish_resize.end',
    'rescue_start': 'compute.instance.rescue.start',
    'rescue_end': 'compute.instance.rescue.end',
    'delete_end': 'compute.instance.delete.end',
    'exists': 'compute.instance.exists',
    'update': 'compute.instance.update',
    'image_exists': 'image.exists',
    'image_create': 'image.create',
    'image_upload': 'image.upload',
    'image_activate': 'image.activate',
    'image_delete': 'image.delete',
    'image_update': 'image.update'
}

strings_pool = [
    't,gr>>4',
    '4e2#26y<c&',
    'a&?<n=-a',
    'l_%2().t40tq!',
    '=#biu@mw@6m%w-5%1%p:fueypk<&',
    ')>4nr',
    '%.v_j$u8h',
    '3l,>2u1^qn^g24e,',
    '$=!$u@v$',
    'y@ex(2+xuu',
    'cx$sk;^ukkd968~z0z4ox,k8u',
    '~)%&hbe&&-;u-ud',
    'om%^id?4#,cx0w3i.o@f',
    '@4~y!i9',
    'th`:4d&bwh9pmtev|',
    '~_j(66gv4l$=.',
    'lq6,!sze(!spa',
    '&xqm(&2p,)v,p223v3^))j1c',
    '(=&@9_;3^h<',
    'psl)',
    't(i)oh^tks,e',
    '4j?__a',
    '4(qf=j.y1;i(vw?~x|~4!;a%',
    'd?7`?b2<mv38ahw!9%fbetl9@>i;',
    '(3+96v,e=_c6#@m-lrow6gon7t`q',
    'y:c>=ul>qa9|ism+h8y-gdd+',
    ',pi%6(6$$uewx5!f(wg<48vjp`p)',
    ',u1x_(',
    '.q`dqi16=g3=x>ii@#2m',
    'r=6uny6!ubq(lf.n&,1?=;48yy',
    'qqv|yl369|tn:@%89m~?;',
    'pd_jamya0#!?c=wzit@&+i&x-_|!:',
    '8)7.-q^32ayic0p);%',
    'z~56%v~5,j&`c<(ej',
    '_g3d(>^|m^e(nq(yw~r^8|1k=p',
    '(njr3bx;$03.(',
    'dom.5,)`z?n@y<gmuv9',
    'p',
    'ss',
    '?u(!g-of-h9<',
    'm;%:m&k_',
    '<|iivj,:6bt5!',
    '+d7kx0y2,:o9u9lx&_;qnfkvt`b',
    ')s1sbor~$p|$o1,sr(0%.rv=_ee',
    'k<95|@=(0e.qr`ge`7?~><=7',
    'xvu)`#q3w^i?1.f<2.e$9?',
    'k&c',
    '8n!9g3<avt96-6el#+lz=4&',
    'gs7_s>j_5i-',
    'sxpd2.t`q`a))hu+'
]

keys_types_pool = [
    ('lbbxki_mvvp_kiweovddbkixquibhgsn_e', 'str'),
    ('ariywoxnkzfxhxwimfctyynihsnctkg', 'int'),
    ('drimvp_jvmgxgmylavhnuiycnoghbvcbwcovia', 'int'),
    ('acdjlacirtgsuwfupflyhszpnriryrwxgqzt', 'datetime'),
    ('tmnve', 'str'),
    ('q_hv_qhwqyixcqlktatgozepedgpngwrhtztmjkmmv_kybd', 'datetime'),
    ('cehuschz_lgwjnsy', 'int'),
    ('ywfjkinseitpmd', 'int'),
    ('vvqtifrjucpeqhx_ibfultrd', 'int'),
    ('akxlsjodyuemxn', 'datetime'),
    ('wjjtnijadpxjyupjypaprbqvj', 'str'),
    ('xbfgumfo_ftofjqlenvgndxxrz', 'datetime'),
    ('ljackcshgbgptngyxlthcxyhjij', 'int'),
    ('r_yeftjwzjgzuuiwdiyd_xmkn', 'int'),
    ('dtezsflfkuxhmjrvlaqfpyqsjyinsaavh', 'int'),
    ('a_przvamnrtarypvucr', 'int'),
    ('uvlogoirkcelkjtjwxbnygschhw_bhslicblqca', 'str'),
    ('wvoqrszidreokxentgnqxch', 'datetime'),
    ('jqtows', 'int'),
    ('cj_zn', 'int'),
    ('xynvkfnczuiwml', 'datetime'),
    ('qxde_modjlhno_misthj', 'datetime'),
    ('iibzoi', 'int'),
    ('agavafohhbxmaakgpukd', 'str'),
    ('gjikvxbwtamvcebvrj_d', 'str'),
    ('ydtoklkcljyrts', 'datetime'),
    ('acm_bmehrpcoyikmzdhhggzadx', 'int'),
    ('eeaqqq_uxztewjwsrshzt', 'int'),
    ('qeuwm_zkwi_ilkuoverrdmumv', 'str'),
    ('uvhoaiuueoezodnaxuiotc_og', 'str'),
    ('pnnfwwlzyrfxpawbafeev_rpbrccvw_zllanv', 'str'),
    ('uwcez', 'datetime'),
    ('xilcas', 'datetime'),
    ('nyqwvgduzax_wmvjkvvepjtbalemnpomszotjcsrdisoz_bd', 'str'),
    ('bxmcqyqnguxvvmhozsl_acslkm_oxiqbjiajtsrs_pvhihy', 'int'),
    ('pqt_eubqrmrf_u_dbuzhuztsaowryknxmlj_ryb_n', 'datetime'),
    ('_qzubpg_nkdh', 'datetime'),
    ('xesbdosjwmy_wrcugsvbpiwcrcctdhcgiyyxwcbrycwj', 'str'),
    ('k_vyir_koggdqylqontahlcnzqopjtyja', 'str'),
    ('ayyxim', 'datetime'),
    ('dleku_xbq', 'int'),
    ('yqejjetp_qurw_zwafygsqrukfh', 'datetime'),
    ('hjyprcoqdeaogfg', 'datetime'),
    ('bthqvdqojyirykeoyknzi_ke_wcvhv_voisrxvdbxzulvqs', 'int'),
    ('meecqvfdgmbbav', 'str'),
    ('xjbgpgqbatqshfwplbo_hksm_gfndyfmirogkfzvytcos', 'str'),
    ('xejorff_ap_ecleumlfxynh_kredynxixp', 'int'),
    ('hovzdjvay', 'str'),
    ('hxjkwhjomhud_mbbyqzdtpbrldclowismhkx', 'datetime'),
    ('npyhkurflgkjdmkjhpvxxqm_gieshhvbg', 'str'),
    ('iknrb', 'str'),
    ('knnyvjwekdyhocz_klujguz', 'str'),
    ('kggjczovo_zieq', 'datetime'),
    ('ejmexarhohsme_wyprjthayjgcbmwoqwezxchppwlvq', 'int'),
    ('urwjvzfsswkjfgyuuoyvsq_jeishx_ojonq', 'str'),
    ('lxwx', 'str'),
    ('fxkv_tizolzynydakycogayjpbqnvwonnsts', 'int'),
    ('yxkgghalxrmusg', 'str'),
    ('nllja_wfnwffzu', 'int'),
    ('ewxhzbriiafnpyqtzlggsdtxuyj_jeaepjj_jcb', 'int'),
    ('acbytvmtyejbzwrbqxxxtjejigefjrehkixzkz', 'str'),
    ('zunsywlbfjqhcroawdkrcqssdhffwhkpuzxftoqqvbe', 'datetime'),
    ('hjxbdtmhcf', 'str'),
    ('iqpshehuwgujjmpsshmtggwodbmqhvgemgo_t', 'int'),
    ('buo_cdaxeqarjlxpvfkatpiobyfridqncgi', 'str'),
    ('gucracpwrvr_ydsdpwcvafhxxhuqpyrjeeb', 'datetime'),
    ('ospncmkctuiovjh_ubwwsabkmmwkzhmsy', 'datetime'),
    ('vugvdwsqjfmbq_kuiomlwhgesnomwnphbllc', 'int'),
    ('axrrqkmwborfxrzufkvrnkywroull', 'int'),
    ('rvwe_cgvwteuxrevzbcvsqagupddlxvcpjsvh_tn', 'int'),
    ('vpedhzjunwr', 'datetime'),
    ('gpdmxyzbyrcxftkvelntd', 'datetime'),
    ('cuyptigfpzxpkneqhxywicgleniuosfxuxtsdefem', 'datetime'),
    ('pc_tkjgy_wnzvk_', 'str'),
    ('szcpvmekrcnqknynwdivncjpj_eeqj', 'int'),
    ('vsrieeygosjxyatxcsbjgwuseevb', 'datetime'),
    ('lvjfnkyqzjxnwdqvqjqgiewwqg', 'datetime'),
    ('qzj_mismvlkoo_ibyxqefnozjnzqkgmbrngfzwoywfrjxmh', 'str'),
    ('cwrntwsiwxeqinrqkvgamahahezbvtoyfwdx', 'int'),
    ('bxogtpzrumoevzil', 'int'),
    ('b_iky', 'datetime'),
    ('prwieqansqbouddycdbbemghnuttc', 'int'),
    ('fli__nscvgs', 'str'),
    ('cx_hfpnbh_kcgzntchtjryemdwwhxjq_ipcfp_vfvlbsdus', 'datetime'),
    ('gjiwnuexmrjkb', 'int'),
    ('hotrjbmvbxqdjyqptuqltenceissougkeuagatqkjb', 'datetime'),
    ('kajrhaaljnbaaqn_vtphjlzprpqtcsabqzji__vjjrjjtsxm', 'int'),
    ('wlylgaccylzlkgqmmqvtokdhyynxawyno_lk', 'datetime'),
    ('kyrwrajfmgvnpzrfhyosj_yctqkzvsfckvvvwniyrrnypf', 'int'),
    ('cxprtldjikhuqcaqupxi_', 'str'),
    ('cpjp', 'str'),
    ('tfapfzysyul_sxmvzdyvxgdzasmvpr', 'int'),
    ('y_rfwvmfummqjus', 'datetime'),
    ('amimoosihuenity', 'int'),
    ('hwwbdrgklwloaabghqzwtauhdendznvgphtsoaexaxe_uwz', 'str'),
    ('onjwvpedqnvwer', 'int'),
    ('tjieilhomjyratpnthqnriuknj', 'int'),
    ('_wjtsebfmwjmrqfswsguufziiibvwqusn', 'int'),
    ('mmwsgjyfhdygmkvflggkdopngmar_sgswpaztbmsrm', 'str'),
    ('mwgzcafgucoiljg_wqdxuptduzuzu', 'datetime'),
    ('umhxivufauroxxwarhwnmmr', 'str'),
    ('ov_ga', 'str'),
    ('t_jjjwfrgx_ktlkqpfsl', 'datetime'),
    ('usqxpvurrujnvsdeoemozclcvjhxkmw_e', 'int'),
    ('dbipetrsnwqyikjzljgaxkhywxfrwgxlb', 'datetime'),
    ('pdasluwdgnin_cogxexewqqfuklvmbfpzigqchikmje', 'str'),
    ('w_xrhwf', 'int'),
    ('bvkmkveieestdozemsqkedcklfijpbh_kxii', 'int'),
    ('goyif_mly_qwnvzo', 'str'),
    ('epigdzdnlswwvutoli_elkn_yg_lnfmhoefds', 'int'),
    ('xppqzm_hpauaiir_wol', 'str'),
    ('lcagieoaxmytyahfylqtsvovuqlawqnp_sesiou_xbgm', 'str'),
    ('hjavkm_zwpipmvxtebdk', 'str'),
    ('qfbhtuxqlccdoikh', 'int'),
    ('bjy_fxgdocbptgglplqalnbsygqdnvnbi', 'datetime'),
    ('thdzszjqjlvkwxbhnwilandkklo', 'int'),
    ('pfhjct', 'str'),
    ('crkqvoc', 'datetime'),
    ('_uuuwdibpjw_aeaw', 'datetime'),
    ('iqqpflbloqocrhqdxis', 'datetime'),
    ('yfiukvphrekwsirbjetzhbiuzamaxjiopudultbs', 'int'),
    ('s_mdpdklihtdkoqzhllykqhpsytr', 'int'),
    ('m_dbooktyydbabbfs_gsrw', 'datetime'),
    ('jndts_vxqjfvqfqnozndbaqhlo', 'int'),
    ('kmbowfwvamjtzvvypkgbfutqepesm', 'str'),
    ('cekzsylbcmofbfserzpvxllomwqt', 'datetime'),
    ('edqnadwfvaklvrsunoxkmzfjquxzh', 'str'),
    ('briitrupwk_xxfgpbzgnbgnpdzyddbvq_sgafdskpmhyix_', 'datetime'),
    ('fgihbj_zxwygxumnmj', 'int'),
    ('lqurhxuhxtk_uushvyahueitu_zqogtbcnmlainwm', 'datetime'),
    ('wd_zafnrfqvbqthxdgmzqbdnpamgis_qkwzfufy', 'str'),
    ('wttxhcesbmbmcbvwbbkxeyyahixbgbbz_phjqtmq', 'datetime'),
    ('rkfwjyrvtwbb', 'datetime'),
    ('mvnpmrtphztwj', 'datetime'),
    ('bcctijtjgkav_zgggdgujlrdojxhrkzdg_xymmp', 'datetime'),
    ('hzvunnluvhruurmfej__vru', 'datetime'),
    ('nemirgrxftyy', 'int'),
    ('plzzjffovr_azxsfxesbltldwyn_rqyblaxuq', 'datetime'),
    ('dbjk', 'datetime'),
    ('fuglgt_ugostmnmauiex', 'str'),
    ('jc__xycovenlwzwvphwwctd', 'str'),
    ('ykowgfyxubwscugxbpsyszpejs', 'int'),
    ('yrjoweskseozfakzetit', 'int'),
    ('bodhbiqihuihwwbfslpopdxrevfcizjhppg', 'datetime'),
    ('t_mlmxbpssien_twiweebwfheyvmia', 'str'),
    ('hz_vksitbyifqpccvkfgxykbyoxv', 'datetime'),
    ('agocpzdabgzubtnxf', 'int'),
    ('xuxvkyhbem', 'datetime'),
    ('r_vlbvoca__bwwosmkdggwxlob_xy_ptmcrej', 'str'),
    ('rfmmbegqisangxxxxslkkenvistazesoy_ttoxvtcaziplji', 'str'),
    ('dbvzxalawqavqchmmfzxmerjeswirspbahyemkd', 'int'),
    ('ki_wmhprb', 'datetime'),
    ('reilnnfxbrozoonerxukeznwretdy_', 'datetime'),
    ('dyqbqgboyond_kym_gwmdtcyzd', 'int'),
    ('hsfoqj', 'datetime'),
    ('iaqfnjmkdffcpem', 'int'),
    ('ttoosldbamcuv', 'int'),
    ('dwaemywcsdidljwpiodhvndmjdcyz', 'datetime'),
    ('yzgk_jlppq_f_jpftqkwbsfyidvlcfjyrs_dqtpjvq', 'str'),
    ('rodrqkiiwkyjfdlqs_wphx_wqmexnfr', 'datetime'),
    ('ksbxfgucrslucfn', 'int'),
    ('oc_mjtnnskmdzridujjwpcge', 'str'),
    ('xbjqtpzsfmzjlx_qvbllywptjne', 'str'),
    ('rhaqhfhih_v', 'str'),
    ('mglwasjxwqahudrxygemgmvsbdgiwt', 'int'),
    ('ckweemtkyfbqnjcunqgexehqlqritewfvcxcnukdmrqerdg', 'datetime'),
    ('ftbnxfyo_dflzdiuhrmy_cwk_zwz_cthgdx', 'datetime'),
    ('akpsthxkurpzsaiyof_jgbgcfeqghtlojvvikbobsfuqs_og', 'int'),
    ('a_svhopdvqatiiszhopvcuowbzapuftf_jdwd__wk', 'datetime'),
    ('ikjolrbkaxycmxcvxymbxldctbp__czpaopkzm', 'int'),
    ('ajppdhmnxlohuthxqzdpeesy', 'datetime'),
    ('_ozkrjeedmlwig', 'str'),
    ('_ornf', 'int'),
    ('_xg_fszsqsmtxeqovjswsvsdto', 'datetime'),
    ('ytbwodpoonzs_ssspvfiwstshmmb_nujvqrwjsgpbldj_yt', 'int'),
    ('ep_bwin_kqzhzxhrplyeo', 'datetime'),
    ('rqpopbomjjn_gcjdctre', 'str'),
    ('nizmvkenjbvlqjiwcumpjciprgxdassvaeuglwgp', 'str'),
    ('jrkdtgrzxvhupv', 'int'),
    ('xkjlufbkuprerguqadcindeugi', 'datetime'),
    ('zsatr_bkyeskpicojndmaryaiaccqe', 'datetime'),
    ('ivjlfqgzcosmctedvitueadgewzdkvgwwviyxcrxxpdi', 'datetime'),
    ('kavlhjanvsoborpfcygeitv', 'int'),
    ('z_kufbsrbpskksfdaktldo', 'datetime'),
    ('zaaqzlylklwdvqt', 'int'),
    ('vxlxlscqlwnhqrsxzquczhaxao', 'datetime'),
    ('iezlrakutngckkzggzabdytzbdlawkgivebadmwv_a', 'datetime'),
    ('_soac_qtoxajym_tzrzregjgpxvrr', 'str'),
    ('rifyofbfxkadyqqwqikdyq_lf', 'str'),
    ('bxwscsska', 'str'),
    ('wwohad_axbczafknvwjmizpdoynqyzqcgmsyxzbi', 'int'),
    ('efoenqhwwtkcnx_pzzxauqjjs_waggvhjjvpv', 'datetime'),
    ('riwxzzqab_wnhtzxrqiucnq_eoxryaib', 'int'),
    ('cnqmggwrmrukwkjelpursdsbcbwztwfnabaz', 'datetime'),
    ('vkemi_wcjrleepusmmvafopdfqxqdr', 'str'),
    ('dkvumyssuxyfilbqwalxroqjcrobiyfteqhocpzercn', 'datetime'),
    ('yqzwhtyzkurru_ouil', 'datetime'),
    ('enaabweeg_euqlzgdaxgecjeswwmzsw_', 'int'),
    ('bxdlm_hrxoegemgcgpxcjixfzt', 'datetime'),
    ('vjdvismqjmtkktgz_zvrmx_myfkivde', 'datetime')
]
